apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: bd-lab-8
data:
  QDRANT_URL: "http://qdrant:6333"
  QDRANT_INPUT_COLLECTION: "products_raw"
  QDRANT_OUTPUT_COLLECTION: "products_clustered"
  DATA_PATH: "/data/raw/products.csv"
  PREPROCESSED_PATH: "/data/processed/preprocessed.parquet"
  PREDICTIONS_PATH: "/data/processed/predictions.parquet"
