qdrant {
  url                = "http://localhost:6333"
  url                = ${?QDRANT_URL}
  api-key            = ""
  api-key            = ${?QDRANT_API_KEY}

  input-collection        = "products_raw"
  input-collection        = ${?QDRANT_INPUT_COLLECTION}
  clustered-collection    = "products_clustered"
  clustered-collection    = ${?QDRANT_OUTPUT_COLLECTION}

  scroll-batch-size  = 1000
  upload-batch-size  = 512
  vector-size        = 5
}

data {
  selected-columns = ["energy_100g", "fat_100g", "carbohydrates_100g", "sugars_100g", "proteins_100g"]
  row-limit        = 1000
  csv-path         = "data/raw/products.csv"
  csv-path         = ${?DATA_PATH}
  csv-separator    = "\t"
  preprocessed-path = "data/processed/preprocessed.parquet"
  preprocessed-path = ${?PREPROCESSED_PATH}
  results-path      = "data/processed/predictions.parquet"
  results-path      = ${?PREDICTIONS_PATH}
}

spark {
  app-name        = "DataMart"
  master          = "local[2]"
  driver-memory   = "2g"
  executor-memory = "1g"
  executor-cores  = 1
  cores-max       = 2
}
